Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.20"
  config.vm.provision "shell", path: "setup.sh"

#  config.vm.provision "shell", inline: <<-SHELL
#    export DEBIAN_FRONTEND=noninteractive
#    sudo apt update
#    sudo apt install -y apache2
#    sudo systemctl enable apache2
#  SHELL
end
